<?php

namespace GCF\MainBundle\Repository;

/**
 * CatLearningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatLearningRepository extends \Doctrine\ORM\EntityRepository
{
}
