<?php

namespace GCF\MainBundle\Repository;

/**
 * CatPublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatPublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
