<?php

namespace GCF\MainBundle\Repository;

/**
 * ElearningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElearningRepository extends \Doctrine\ORM\EntityRepository
{
}
