<?php

namespace GCF\MainBundle\Repository;

/**
 * EtatPubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatPubRepository extends \Doctrine\ORM\EntityRepository
{
}
