<?php

namespace GCF\MainBundle\Repository;

/**
 * FocusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FocusRepository extends \Doctrine\ORM\EntityRepository
{
}
