<?php

namespace GCF\MainBundle\Repository;

/**
 * GouveroratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GouvernoratRepository extends \Doctrine\ORM\EntityRepository
{
}
