<?php

namespace GCF\MainBundle\Repository;

/**
 * SecteurActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurActeurRepository extends \Doctrine\ORM\EntityRepository
{
}
