<?php

namespace GCF\MainBundle\Repository;

/**
 * SecteurProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurProjetRepository extends \Doctrine\ORM\EntityRepository
{
}
