imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
        
# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    form_themes:
        - '@SonataMedia/Form/media_widgets.html.twig'
        
# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_generate_proxy_classes: %kernel.debug%
#        auto_mapping: true
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_translator:
                        type: annotation
                        prefix: Gedmo\Translator\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
                        is_bundle: false
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias: GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false

                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~


    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sonata_admin:
    title: GCF Admin
#    title_logo: img/logo_small.png
    title_logo: /assets/images/GCF-white-LOGO-Blue.png

    options:
        html5_validate:    true     # enable or disable html5 form validation
        confirm_exit:      true     # enable or disable a confirmation before navigating away
        use_select2:       true     # enable or disable usage of the Select2 jQuery library
        use_icheck:        true     # enable or disable usage of the iCheck library
        use_bootlint:      false    # enable or disable usage of Bootlint
        use_stickyforms:   true     # enable or disable the floating buttons
        form_type:         standard # can also be 'horizontal'

    templates:
        edit:              '@SonataAdmin/CRUD/edit.html.twig'
        tab_menu_template: '@SonataAdmin/Core/tab_menu_template.html.twig'
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'


sonata_block:
    default_contexts: [cms]
    blocks:

        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_translation:
    locales: [fr, en, ar_TN]
    default_locale: fr
    # here enable the types you need
    gedmo:
        enabled: true
    knplabs:
        enabled: false
    #phpcr:
    #    enabled: true
stof_doctrine_extensions:
    default_locale: fr_FR
    uploadable:
        # Default file path: This is one of the three ways you can configure the path for the Uploadable extension
        default_file_path:       "%kernel.root_dir%/../web/uploads"
    orm:
        default:
            tree: true
            timestampable: false # not needed: listeners are not enabled by default
            translatable: true

sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            #directory:  "%kernel.root_dir%/../public/uploads/media" #flex
            directory:  "%kernel.root_dir%/../web/uploads/media" #non-flex
            create:     false
    providers:
        image:
            resizer: sonata.media.resizer.square
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia

white_october_breadcrumbs: ~


easy_admin:
    site_name: 'GCF Admin'
    design:
        color_scheme: 'light'
        menu:
            - label: 'Acteurs'
              icon: 'users'
              children:
                - { label: 'Liste Acteurs', icon: 'list', entity: 'Acteur' }
                - { label: 'Secteurs', icon: 'folder-open', entity: 'SecteurActeur' }

            - label: 'Projets'
              icon: 'th-large'
              children:
                - { label: 'Liste Projets', icon: 'list', entity: 'Projet' }    
                - { label: 'Focus', icon: 'folder-open', entity: 'Focus' }
                - { label: 'Secteurs', icon: 'folder-open', entity: 'SecteurProjet' }

            - label: 'Publications'
              icon: 'pencil'
              children:
                - { label: 'Liste Publications', icon: 'list', entity: 'Publication' }

            - label: 'Elearning'
              icon: 'paperclip'
              children:
                - { label: 'Liste Elearning', icon: 'list', entity: 'Elearning' }
                - { label: 'Catégories', icon: 'folder-open', entity: 'CatLearning' }

            - label: 'Événements'
              icon: 'calendar'
              children:
                - { label: 'Liste Événements', icon: 'list', entity: 'Event' }

            - label: 'Paramètres'
              icon: 'cog'
              children:
                - { label: 'Gouvernorats', icon: 'map-marker', entity: 'Gouvernorat' }
                - { label: 'États Pub', icon: 'edit', entity: 'EtatPub' }

            - label: 'About'
              children:
                - { label: 'Help', url: 'http://example.com/external-docs'  }
                - { label: 'Docs', url: 'http://example.com/external-docs' }
    entities:
        Acteur:
            class: GCF\MainBundle\Entity\Acteur
            form:
                fields:
                    #- id
                    - { property: 'nomFr', type: 'text' }
                    - { property: 'nomEn', type: 'text' }
                    - { property: 'nomAr', type: 'text' }
                    - { property: 'logo', type: 'file', label: 'Upload Logo', help: 'Selectionnez une image à uploader'}
                    - { property: 'descriptionFr', type: 'textarea' }
                    - { property: 'descriptionEn', type: 'textarea' }
                    - { property: 'descriptionAr', type: 'textarea' }
                    - { property: 'hierarchie', type: 'text' }
                    - { property: 'missionFr', type: 'text' }
                    - { property: 'missionEn', type: 'text' }
                    - { property: 'missionAr', type: 'text' } 
                    - { property: 'responsableFr', type: 'text' }
                    - { property: 'responsableEn', type: 'text' }
                    - { property: 'responsableAr', type: 'text' }
                    - { property: 'contact', type: 'text' }
                    - { property: 'critiqueFr', type: 'textarea' }
                    - { property: 'critiqueEn', type: 'textarea' }
                    - { property: 'critiqueAr', type: 'textarea' }
                    
                    - { property: 'secteurActeur', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\SecteurActeur' } }
                    - { property: 'acteurParent', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\Acteur' } }

                    #- { property: 'email', type: 'email', type_options: { trim: true } }
                    #- { property: 'interests', type_options: { expanded: true, multiple: true } }
                    #- { property: 'updated_at', type_options: { widget: 'single_text' } }
            list:
                fields: ['nomFr', 'nomAr', 'logo', 'responsableFr', 'contact']
                
        SecteurActeur:
            class: GCF\MainBundle\Entity\SecteurActeur
            form:
                fields:
                    - { property: 'nomFr', type: 'text' }
                    - { property: 'nomEn', type: 'text' }
                    - { property: 'nomAr', type: 'text' }
                    - { property: 'secteurActeurParent', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\SecteurActeur' } }
            list:
                fields: ['nomFr', 'nomAr']
                
        Projet:
            class: GCF\MainBundle\Entity\Projet
            form:
                fields:
                    - { property: 'nomFr', type: 'text' }
                    - { property: 'nomEn', type: 'text' }
                    - { property: 'nomAr', type: 'text' }
                    - { property: 'gouvernorat', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\Gouvernorat' } }
                    - { property: 'acteur', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\Acteur' } }
                    - { property: 'secteurProjet', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\SecteurProjet' } }
                    
            list:
                fields: ['nomFr', 'nomAr']
                
        SecteurProjet:
            class: GCF\MainBundle\Entity\SecteurProjet
            form:
                fields:
                    - { property: 'nomFr', type: 'text' }
                    - { property: 'nomEn', type: 'text' }
                    - { property: 'nomAr', type: 'text' }
                    - { property: 'couleur', type: 'text' }
                    - { property: 'secteurProjetParent', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\SecteurProjet' } }
            list:
                fields: ['nomFr', 'nomAr']
                
        Focus:
            class: GCF\MainBundle\Entity\Focus
            form:
                fields:
                    - { property: 'nomFr', type: 'text' }
                    - { property: 'nomEn', type: 'text' }
                    - { property: 'nomAr', type: 'text' }
                    
            list:
                fields: ['nomFr', 'nomAr']
            
        Publication:
            class: GCF\MainBundle\Entity\Publication
            form:
                fields:
                    - { property: 'titreFr', type: 'text' }
                    - { property: 'titreEn', type: 'text' }
                    - { property: 'titreAr', type: 'text' }
                    - { property: 'contenuFr', type: 'textarea' }
                    - { property: 'contenuEn', type: 'textarea' }
                    - { property: 'contenuAr', type: 'textarea' }
                    - { property: 'emailBloggeur', type: 'email' }
                    - { property: 'projet', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\Projet' } }
            list:
                fields: ['titreFr', 'titreAr']
        Elearning:
            class: GCF\MainBundle\Entity\Elearning
            
        CatLearning:
            class: GCF\MainBundle\Entity\CatLearning
            form:
                fields:
                    - { property: 'nomFr', type: 'text' }
                    - { property: 'nomEn', type: 'text' }
                    - { property: 'nomAr', type: 'text' }
                    - { property: 'catLearningParent', type: 'easyadmin_autocomplete', type_options: { class: 'GCF\MainBundle\Entity\CatLearning' } }
            list:
                fields: ['nomFr', 'nomAr']
                
        Event:
            class: GCF\MainBundle\Entity\Event 
          
        Gouvernorat:
            class: GCF\MainBundle\Entity\Gouvernorat
            form:
                fields:
                    - { property: 'nomFr', type: 'text' }
                    - { property: 'nomEn', type: 'text' }
                    - { property: 'nomAr', type: 'text' }
                    
            list:
                fields: ['nomFr', 'nomAr']
        EtatPub:
            class: GCF\MainBundle\Entity\EtatPub
            
