services:
#    gcf_main.example:
#        class: GCF\MainBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    GCF\MainBundle\DataFixtures\ORM\ActeurFixtures:
        tags: [doctrine.fixture.orm]

    GCF\MainBundle\DataFixtures\ORM\SecteurActeurFixtures:
        tags: [doctrine.fixture.orm]



    admin.Acteur:
        class: GCF\MainBundle\Admin\ActeurAdmin
        arguments: [~, GCF\MainBundle\Entity\Acteur, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Acteurs, label: Gestion les Acteurs }
        public: true
    admin.SecteurActeur:
        class: GCF\MainBundle\Admin\SecteurActeurAdmin
        arguments: [~, GCF\MainBundle\Entity\SecteurActeur, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Acteurs, label: Secteurs }
        public: true
        
    admin.Projet:
        class: GCF\MainBundle\Admin\ProjetAdmin
        arguments: [~, GCF\MainBundle\Entity\Projet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Projets, label: Gestion les Projets }
        public: true
        
    admin.SecteurProjet:
        class: GCF\MainBundle\Admin\SecteurProjetAdmin
        arguments: [~, GCF\MainBundle\Entity\SecteurProjet, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Projets, label: Secteurs }
        public: true

    admin.Focus:
        class: GCF\MainBundle\Admin\FocusAdmin
        arguments: [~, GCF\MainBundle\Entity\Focus, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Projets, label: Focus }
        public: true

    admin.Publication:
        class: GCF\MainBundle\Admin\PublicationAdmin
        arguments: [~, GCF\MainBundle\Entity\Publication, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Publications, label: Gestion les Publications }
        public: true
        
    admin.Elearning:
        class: GCF\MainBundle\Admin\ElearningAdmin
        arguments: [~, GCF\MainBundle\Entity\Elearning, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Elearning, label: Gestion elearning }
        public: true
        
    admin.CatLearning:
        class: GCF\MainBundle\Admin\CatLearningAdmin
        arguments: [~, GCF\MainBundle\Entity\CatLearning, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Elearning, label: Categories Elearning }
        public: true
        
    admin.gouvernorats:
        class: GCF\MainBundle\Admin\GouvernoratAdmin
        arguments: [~, GCF\MainBundle\Entity\Gouvernorat, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Autres, label: Gouvernorats }
        public: true